### ISSUE TITLE
Move documentation off readme.io and use a documentation generator

### ISSUE THREAD

**Issue by NathanFlurry** [vapor/website#3]
# Move documentation off readme.io and use a documentation generator
- Author(s): [Nathan Flurry](https://github.com/nathanflurry)
## Introduction

The idea here is to move documentation off readme.io and also starting using a documentation generator to provide online documentation.
## Motivation

Contributing to documentation on readme.io isn't very ideal, in my opinion. It would be nice to be able to contribute via GitHub in some way.

In addition, when a new user wants to evaluate a framework, they usually look at the online documentation first to get a feel for the API. By not providing that, it may deter some users.
## Proposed solution

As for the tutorials on readme.io, I propose that we add the documentation in Markdown on this website. One advantage of hosting the content here is that we could eventually include interactive tutorials in sandboxed environments for users to try out Vapor (see qutheory/vapor#292).

As for the generated documentation, the easiest solution would be to use [jazzy](https://github.com/realm/jazzy) and throw a theme on top of it to make it look pretty.
## Impact

This change would make the framework seem much more approachable.
## Alternatives considered

Another alternative is to simply use the Wiki on GitHub. It may not be glamorous, but – in my opinion – it would be the most functional solution.

**Comment by tanner0101** [comment]
Wikis on GitHub don't allow PRs or collaboration unfortunately. But I like the idea of moving the docs from readme.io into their own repo on GitHub. `qutheory/docs`. 

The only issue here is that it would take a bit of time to convert the docs to a markdown format since I don't believe readme.io let's you export them as markdown.

Additionally configuring something like Jazzy and figuring out how to run it when the docs change would also take time.
