### ISSUE TITLE
Right to left language

### ISSUE THREAD

**Issue by hsharghi** [vapor/website#39]
Does the website support rtl design? 
I was going to PR localization for a rtl language.

**Comment by tanner0101** [comment]
@hsharghi we use `vue-i18n`. I tried googling if they support RTL, and all I found was this: https://github.com/kazupon/vue-i18n/issues/182

I'm not sure what that means, but it seems like they don't need to support / it should work.

**Comment by Mordil** [comment]
@hsharghi Could you provide a little insight into what you think you need in order to support RTL languages?

From the website, I don't think there's necessarily any design thought that directly makes it LTR other than the Vapor logo in the top left.

During Vapor 4's redesign we could try to be mindful of such elements and work to dynamically update the specific details that make it more LTR natural.

**Comment by hsharghi** [comment]
@Mordil
Main change in the UI would be moving side bar menu to the right side of screen. 
And the paragraphs would be justified to the right instead of left. 
Some icons may need to be changed. Eg.  ‘>’ icon in front of menu items will be replaced with ‘<‘. 
Normally <dir=“rtl”> tag will handle all the necessary changes. 
I think it’s better that I test it in my local environment and see what will happen.

**Comment by Mordil** [comment]
@hsharghi This is for the site [vapor.codes](https://vapor.codes), right? I'm not understanding what elements on that page you're referring to.

**Comment by hsharghi** [comment]
@tanner thanks, I’ll check `vue-i18n` docs for rtl

**Comment by hsharghi** [comment]
@Mordil I’m referring to https://docs.vapor.codes

**Comment by Mordil** [comment]
@hsharghi Ah - then this should move to [vapor/documentation](https://github.com/vapor/documentation)

This repo is only responsible for [vapor.codes](https://vapor.codes)
